# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[gomod] "
    groups:
      internal-dependencies:
        patterns:
          - "*open-edge-platform*"
          - "github.com/open-edge-platform/*"
      k8s-updates:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
        exclude-patterns:
          - "*open-edge-platform*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[gha] "
  - package-ecosystem: "docker"
    directory: "/"  # Changed from "directories" to "directory"
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[docker] "
