{
 "title": "Cluster Orch - Cluster Connect Gateway",
 "description": "Collection of cluster orchestration metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total{namespace=\"$namespace\"},job)"
    }
   },
   {
    "name": "namespace",
    "query": "orch-cluster,capi-operator-system,capi-system,cattle-fleet-system,orch-cluster"
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total{namespace=~\"$namespace\", job=~\"$job\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Controller metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Reconciliation Count Per Controller",
   "type": "timeseries",
   "description": "Total number of reconciliations per controller",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{job=\"cluster-connect-gateway-controller-metrics\", namespace=\"orch-cluster\"}[5m])) by (instance, pod)",
     "legendFormat": "{{instance}} {{pod}}"
    }
   ]
  },
  {
   "title": "Reconciliation Error Count Per Controller",
   "type": "timeseries",
   "description": "Total number of reconciliation errors per controller",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_errors_total{job=\"$job\", namespace=\"$namespace\"}[5m])) by (instance, pod)",
     "legendFormat": "{{instance}} {{pod}}"
    }
   ]
  },
  {
   "title": "Seconds For Items Stay In Queue (before being requested) (P50, P90, P99)",
   "type": "timeseries",
   "description": "How long in seconds an item stays in workqueue before being requested",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"$job\", namespace=\"$namespace\"}[5m])) by (instance, name, le))",
     "legendFormat": "P50 {{name}} {{instance}} "
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"$job\", namespace=\"$namespace\"}[5m])) by (instance, name, le))",
     "legendFormat": "P90 {{name}} {{instance}} "
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"$job\", namespace=\"$namespace\"}[5m])) by (instance, name, le))",
     "legendFormat": "P99 {{name}} {{instance}} "
    }
   ]
  },
  { "title": "Work Queue Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Seconds Processing Items From WorkQueue (P50, P90, P99)",
   "type": "timeseries",
   "description": "How long in seconds processing an item from workqueue takes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(workqueue_work_duration_seconds_bucket{job=\"$job\", namespace=\"$namespace\"}[5m])) by (instance, name, le))",
     "legendFormat": "P50 {{name}} {{instance}} "
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(workqueue_work_duration_seconds_bucket{job=\"$job\", namespace=\"$namespace\"}[5m])) by (instance, name, le))",
     "legendFormat": "P90 {{name}} {{instance}} "
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_work_duration_seconds_bucket{job=\"$job\", namespace=\"$namespace\"}[5m])) by (instance, name, le))",
     "legendFormat": "P99 {{name}} {{instance}} "
    }
   ]
  },
  {
   "title": "Work Queue Add Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=\"$job\", namespace=\"$namespace\"}[5m])) by (instance, name)",
     "legendFormat": "{{name}} {{instance}}"
    }
   ]
  },
  {
   "title": "Work Queue Retries Rate",
   "type": "timeseries",
   "description": "Total number of retries handled by workqueue",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_retries_total{job=\"$job\", namespace=\"$namespace\"}[5m])) by (instance, name)",
     "legendFormat": "{{name}} {{instance}} "
    }
   ]
  },
  {
   "title": "Workqueue depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "workqueue_depth{job=\"$job\", namespace=\"$namespace\"}",
     "legendFormat": "{{name}} {{instance}}"
    }
   ]
  },
  { "title": "Gateway metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Request Latency Percentages: 0.5s, 2.5s, 5s, 10s+ ",
   "type": "bargauge",
   "description": "Statistic for /kubernetes endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((rate(request_latency_seconds_bucket{le=\"2.5\"}[5m]) - rate(request_latency_seconds_bucket{le=\"0.5\"}[5m])) / rate(request_latency_seconds_count[5m])) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "((rate(request_latency_seconds_bucket{le=\"5\"}[5m]) - rate(request_latency_seconds_bucket{le=\"2.5\"}[5m])) / rate(request_latency_seconds_count[5m])) * 100",
     "legendFormat": "0.5s-2.5s"
    },
    {
     "expr": "((rate(request_latency_seconds_bucket{le=\"10\"}[5m]) - rate(request_latency_seconds_bucket{le=\"5\"}[5m])) / rate(request_latency_seconds_count[5m])) * 100",
     "legendFormat": "2.5s-5s"
    },
    {
     "expr": "((rate(request_latency_seconds_count[5m]) - rate(request_latency_seconds_bucket{le=\"10\"}[5m])) / rate(request_latency_seconds_count[5m])) * 100",
     "legendFormat": "5s-10s"
    }
   ]
  },
  {
   "title": "Kubeconfig Retrieval Latency Percentages: 0.5s, 2.5s, 5s, 10s+",
   "type": "bargauge",
   "description": "This histogram illustrates the duration required to obtain the secrets from kubeapi, which are essential for authorizing a client with the downstream cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(kubernetes_secret_kubeconfig_retrieval_duration_seconds_bucket{le=\"0.5\"}[5m]) / rate(kubernetes_secret_kubeconfig_retrieval_duration_seconds_count[5m])) * 100",
     "legendFormat": "=<0.5s"
    },
    {
     "expr": "((rate(kubernetes_secret_kubeconfig_retrieval_duration_seconds_bucket{le=\"2.5\"}[5m]) - rate(kubernetes_secret_kubeconfig_retrieval_duration_seconds_bucket{le=\"0.5\"}[5m])) / rate(kubernetes_secret_kubeconfig_retrieval_duration_seconds_count[5m])) * 100",
     "legendFormat": "0.5s-2.5s"
    },
    {
     "expr": "((rate(kubernetes_secret_kubeconfig_retrieval_duration_seconds_bucket{le=\"5\"}[5m]) - rate(kubernetes_secret_kubeconfig_retrieval_duration_seconds_bucket{le=\"2.5\"}[5m])) / rate(kubernetes_secret_kubeconfig_retrieval_duration_seconds_count[5m])) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "((rate(kubernetes_secret_kubeconfig_retrieval_duration_seconds_bucket{le=\"10\"}[5m]) - rate(kubernetes_secret_kubeconfig_retrieval_duration_seconds_bucket{le=\"5\"}[5m])) / rate(kubernetes_secret_kubeconfig_retrieval_duration_seconds_count[5m])) * 100",
     "legendFormat": "5s-10s"
    },
    {
     "expr": "((rate(kubernetes_secret_kubeconfig_retrieval_duration_seconds_count[5m]) - rate(kubernetes_secret_kubeconfig_retrieval_duration_seconds_bucket{le=\"10\"}[5m])) / rate(kubernetes_secret_kubeconfig_retrieval_duration_seconds_count[5m])) * 100",
     "legendFormat": "10s+"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(request_latency_seconds_bucket[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Kubeconfig Retrieval Latency",
   "type": "heatmap",
   "description": "This heatmap illustrates the duration required to obtain the secrets from kubeapi, which are essential for authorizing a client with the downstream cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(kubernetes_secret_kubeconfig_retrieval_duration_seconds_bucket[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Remote Dialer Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(session_server_total_add_websocket_session - (session_server_total_remove_websocket_session or (0 * session_server_total_add_websocket_session)))",
     "legendFormat": "{{clientkey}} {{pod}}"
    }
   ]
  },
  {
   "title": "Proxied http response codes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(proxied_http_response_codes{code=~\"2..\"}[5m])) / sum(rate(proxied_http_response_codes[5m]))) * 100",
     "legendFormat": "2XX"
    },
    {
     "expr": "(sum(rate(proxied_http_response_codes{code=~\"4..\"}[5m])) / sum(rate(proxied_http_response_codes[5m]))) * 100",
     "legendFormat": "4XX"
    },
    {
     "expr": "(sum(rate(proxied_http_response_codes{code=~\"5..\"}[5m])) / sum(rate(proxied_http_response_codes[5m]))) * 100",
     "legendFormat": "5XX"
    },
    {
     "expr": "(sum(rate(proxied_http_response_codes{code!~\"2..|4..|5..\"}[5m])) / sum(rate(proxied_http_response_codes[5m]))) * 100",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Data Transmitted by Remote Dialer Sessions (Top 20)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(20,session_server_total_transmit_bytes)",
     "legendFormat": "{{clientkey}} {{pod}}"
    }
   ]
  }
 ]
}