# This rule is not used by the project cluster-connect-gateway itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over cluster.edge-orchestrator.intel.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cluster-connect-gateway
    app.kubernetes.io/managed-by: kustomize
  name: clusterconnection-admin-role
rules:
- apiGroups:
  - cluster.edge-orchestrator.intel.com
  resources:
  - clusterconnects
  verbs:
  - '*'
- apiGroups:
  - cluster.edge-orchestrator.intel.com
  resources:
  - clusterconnects/status
  verbs:
  - get
