apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: RKE2ControlPlane
metadata:
  name: sample-control-plane
spec:
  replicas: 1
  version: v1.30.3+rke2r1
  serverConfig:
    cni: calico
  rolloutStrategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1