//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: (C) 2025 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterConnect) DeepCopyInto(out *ClusterConnect) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterConnect.
func (in *ClusterConnect) DeepCopy() *ClusterConnect {
	if in == nil {
		return nil
	}
	out := new(ClusterConnect)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterConnect) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterConnectList) DeepCopyInto(out *ClusterConnectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterConnect, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterConnectList.
func (in *ClusterConnectList) DeepCopy() *ClusterConnectList {
	if in == nil {
		return nil
	}
	out := new(ClusterConnectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterConnectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterConnectSpec) DeepCopyInto(out *ClusterConnectSpec) {
	*out = *in
	if in.ClusterRef != nil {
		in, out := &in.ClusterRef, &out.ClusterRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.ServerCertRef != nil {
		in, out := &in.ServerCertRef, &out.ServerCertRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.ClientCertRef != nil {
		in, out := &in.ClientCertRef, &out.ClientCertRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterConnectSpec.
func (in *ClusterConnectSpec) DeepCopy() *ClusterConnectSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterConnectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterConnectStatus) DeepCopyInto(out *ClusterConnectStatus) {
	*out = *in
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	in.ConnectionProbe.DeepCopyInto(&out.ConnectionProbe)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterConnectStatus.
func (in *ClusterConnectStatus) DeepCopy() *ClusterConnectStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterConnectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionProbeState) DeepCopyInto(out *ConnectionProbeState) {
	*out = *in
	in.LastProbeTimestamp.DeepCopyInto(&out.LastProbeTimestamp)
	in.LastProbeSuccessTimestamp.DeepCopyInto(&out.LastProbeSuccessTimestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionProbeState.
func (in *ConnectionProbeState) DeepCopy() *ConnectionProbeState {
	if in == nil {
		return nil
	}
	out := new(ConnectionProbeState)
	in.DeepCopyInto(out)
	return out
}
