# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

{{ if .Values.openpolicyagent.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cluster-connect-gateway.fullname" . }}-opa-rego-v2
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
{{ (.Files.Glob "files/openpolicyagent/*.rego").AsConfig | indent 2 }}
{{- end}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cluster-connect-gateway.fullname" . }}-dashboards-orchestrator
  labels:
    grafana_dashboard: "orchestrator"
    {{- include "cluster-connect-gateway.labels" . | nindent 4 }}
  {{- with .Values.gateway.metrics.dashboardAdminFolder }}
  annotations:
    grafana_folder: {{ . }}
  {{- end }}
data:
{{ (.Files.Glob "files/dashboards/*.json").AsConfig | indent 2 }}
