# yamllint disable-file
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cluster-connect-gateway.fullname" . }}
spec:
  selector:
    app: {{ template "cluster-connect-gateway.fullname" . }}-gateway
  type: {{ .Values.gateway.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.gateway.service.port }}
      targetPort: {{ .Values.gateway.listenPort }}
