# yamllint disable-file
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "cluster-connect-gateway.labels" . | nindent 4 }}
  name: {{ template "cluster-connect-gateway.serviceAccountName" . }}
{{- end }}