# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

agent:
  image:
    registry:
      name: registry-rs.edgeorchestration.intel.com
    repository: edge-orch/cluster/connect-agent
    tag: 1.0.6
