# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---

name: Pre-Merge CI Pipeline
  
on:
  pull_request:
    branches:
      - main
      - release-*
  workflow_dispatch: 

permissions: {}

jobs:
  pre-merge:
    permissions:
      contents: read
    uses: open-edge-platform/orch-ci/.github/workflows/pre-merge.yml@0.1.23
    with:
      bootstrap_tools: "base,go"
      cache_go: true
      remove_cache_go: true
      run_security_scans: true
      run_version_check: true
      run_dep_version_check: true
      run_build: true
      run_lint: true
      run_test: true
      run_validate_clean_folder: false
      run_docker_build: true
      run_docker_push: false
      run_helm_build: true
      run_helm_push: false
      run_artifact: false
      version_suffix: "-pr-${{ github.event.number }}"
    secrets:  # zizmor: ignore[secrets-inherit]
      inherit
